
name: PRODUCT_UPDATE_ENVIRONMENT_TAGS

on:   
  workflow_dispatch: 
    inputs:
      app1_tag:
        type: string
        required: false
      app2_tag:
        type: string
        required: false
      environment:
        type: choice
        required: true
        options: ['dev','prod','qa']
        default: "dev"
  
  workflow_call: 
    inputs: 
      app1_tag:
        type: string
        required: false
      app2_tag:
        type: string
        required: false
      environment:
        type: string
        required: true
    secrets:
      CLOUD_ARTIFACTORY_PASS:
        required: true
      CLOUD_ARTIFACTORY_USER:
        required: true

jobs:
  update-environment-tags:
    env:
      REGISTRY: mckinsey-docker.jfrog.io
    runs-on: [ubuntu-latest]
    permissions: 
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::468804646140:role/role-migfactory-14313-git-provisioningagent
          aws-region: us-east-1
          
